query User($username: String) {
    users: userInfos(where: { user: { username: $username } }) {
        id
        firstname
        lastname
        city
        about
        status
        profession
        brief
        state
        weekAvailability {
            dayName
            availableAt
        }
        profileImg {
            url
        }
    }
}
