query User($username: String) {
    users: userInfos(where: { user: { username: $username } }) {
        about
        profileSections {
            title
            content
            img {
                url
            }
        }
    }
}
