query User($username: String) {
    users: userInfos(where: { user: { username: $username } }) {
        firstname
        lastname
        city
        state
        brief
        profileImg {
            url
        }

        tags {
        	label
        }

        badges {
            label
        }
        avgReviewScore
    }
}
