query UserInfo($categories: [String], $tags: [String], $searchQuery: [String], $scores: [Int]) {
  users: userInfos(
    where: {
      category: { Category_contains: $categories },
      tags: { label_contains: $tags},
      _where: {
        _or: [
          {firstname_contains: $searchQuery},
          {lastname_contains: $searchQuery}
        ]
      }
      avgReviewScore_gte: $scores
    }
  ) {
    user {
      username
    }
    firstname
    lastname
    badges {
      label
    }
    location: city
    status
    tags {
      label
    }
    avgReviewScore
    brief
    profileImg {
      url
    }
    category {
      Category
    }
  }
}