query UserInfo($category: [String]){
    users:userInfos(where: { category: { Category_contains: $category } }) {
        firstname
        lastname
    		badges {
          label
        }
    		location: city
    		status
    		tags {
          tag {
            label
          }
        }
    		avgReviewScore
    		brief
    		profileImg {
          url
        }
    		category {
          Category
        }
    }
}